---
- name: Setting up Kodo Endpoints Server FQDN
  set_fact:
    server_fqdn: "{{ inventory_hostname }}"
  when: server_fqdn is undefined

- name: Using the following Kodo Endpoints Server FQDN
  debug:
    msg: "Kodo Endpoints Server FQDN: {{ server_fqdn }}"

- name: Add MariaDB repository
  yum_repository:
    name: MariaDB
    description: MariaDB repository
    baseurl: "{{ mariadb_repo_url }}"
    gpgkey: "{{ mariadb_repo_gpg_key }}"
    gpgcheck: yes

- name: Ensure MariaDB repository on CentOS/RHEL 8 has 'module_hotfixes' option enabled
  ini_file:
    path: /etc/yum.repos.d/MariaDB.repo
    section: MariaDB
    option: module_hotfixes
    value: "1"
  when: ansible_distribution_major_version|int >= 8

- name: Add Kodo Endpoints repository
  yum_repository:
    name: kodo-endpoints
    description: Kodo Endpoints repo
    baseurl: "{{ kodo_repo }}"
    gpgcheck: no

- name: Install Kodo Endpoints Server and dependencies
  yum:
    name:
      - kodo-for-endpoints
      - python3-PyMySQL
    state: present

- name: Start and enable MariaDB service
  service:
    name: mariadb
    daemon-reload: yes
    state: started
    enabled: yes

- name: Secure database
  import_tasks: secure_mariadb.yml

- name: List existing databases
  mysql_info:
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    filter:
      - databases
  register: db_list

- name: Initialize Kodo Endpoints Server
  shell: "{{ kodo_init_script_path }} --dbrootpassword {{ mariadb_root_password }}"
  when: "kodo_db_name not in db_list.databases"

- name: Start and enable Kodo Endpoints Server service
  service:
    name: kodo-for-endpoints
    daemon-reload: yes
    state: started
    enabled: yes

- name: Start and enable firewalld service
  service:
    name: firewalld
    daemon-reload: yes
    state: started
    enabled: yes

- name: Firewall - open port 8181
  firewalld:
    port: 8181/tcp
    zone: public
    permanent: yes
    immediate: yes
    state: enabled

- name: Firewall - redirect port 443 to 8181
  firewalld:
    rich_rule: "rule family=ipv4 forward-port port=443 protocol=tcp to-port=8181"
    zone: public
    permanent: yes
    immediate: yes
    state: enabled

- name: Login to Kodo
  uri:
    url: "https://{{ server_fqdn }}:8181/api/admin/auth/login"
    method: POST
    body:
      username: "{{ kodo_kodoadmin_user }}"
      password: "{{ kodo_kodoadmin_pass }}"
    validate_certs: false
    return_content: true
    body_format: json
  register: resp_login
  retries: 100
  delay: 5
  until: resp_login is not failed

- set_fact:
    token: "{{ resp_login.json.token }}"

- name: Set deployment server
  uri:
    url: "https://{{ server_fqdn }}:8181/api/admin/instance-settings/general"
    method: PUT
    body:
      allowedIpsForKodoAdmin:
      deploymentServerName: "{{ server_fqdn }}"
    headers:
      Authorization: "Bearer {{ token }}"
    body_format: json
    status_code: 204
    validate_certs: false

- set_fact:
    isp_fqdn: "localhost"
  when: isp_fqdn == server_fqdn

- name: Configure IBM Spectrum Protect access
  uri:
    url: "https://{{ server_fqdn }}:8181/api/admin/instance-settings/tsm"
    method: PUT
    body:
      address: "{{ isp_fqdn }}"
      node: "{{ isp_service_node_name }}"
      port: "{{ isp_dsmsys_tcpport|int }}"
      useSsl: false
      collectDeduplicationStats: false
      nextExpireInventoryDate: "{{ ansible_date_time.epoch|int * 1000 }}"
      expireInventoryInterval: 21600000
      expireInventoryResource: 4
      fetchingDeduplicationStatsInterval: 0
    headers:
      Authorization: "Bearer {{ token }}"
    body_format: json
    status_code: 204
    validate_certs: false

- name: Configure IBM Spectrum Protect password
  uri:
    url: "https://{{ server_fqdn }}:8181/api/admin/instance-settings/tsm/password"
    method: PUT
    body:
      password: "{{ isp_service_node_password }}"
    headers:
      Authorization: "Bearer {{ token }}"
    body_format: json
    status_code: 204
    validate_certs: false