---
- name: Try to access DB without password
  mysql_info:
    login_unix_socket: "/var/lib/mysql/mysql.sock"
    login_user: root
    filter:
      - version
  ignore_errors: yes
  register: db_version

- name: MariaDB - set the root password
  mysql_user:
    login_unix_socket: "/var/lib/mysql/mysql.sock"
    name: root
    password: "{{ mariadb_root_password }}"
  when: db_version is not failed

- name: MariaDB - secure the root user
  mysql_user:
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    user: root
    password: "{{ mariadb_root_password }}"
    host: "{{ item }}"
  with_items:
    - "::1"
    - "127.0.0.1"
    - "localhost"
    - "{{ ansible_fqdn }}"

- name: MariaDB - delete anonymous server user
  mysql_user:
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    user: ""
    host_all: yes
    state: absent

- name: MariaDB - remove the test database
  mysql_db:
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    db: test
    state: absent